export enum ToolName {
  CONTENT_READING = 'content_reading',
  CONFIRMATION = 'confirmation',
  ASK_USER = 'askUser',
  EDIT = 'edit',
  // ADD_TABLE_COLUMN = 'edit:add_table_column',
  // REPLACE_BY_LINES = 'edit:replace_by_lines',
  // INSERT = 'edit:insert',
  // REPLACE_BY_PATTERN = 'edit:replace_by_pattern',
  // UPDATE_TABLE_COLUMN = 'edit:update_table_column',
  // DELETE_TABLE_COLUMN = 'edit:delete_table_column',
  GREP = 'grep',
  EXISTS = 'exists',
  CREATE = 'create',
  DELETE = 'delete',
  COPY = 'copy',
  RENAME = 'rename',
  MOVE = 'move',
  LIST = 'list',
  UPDATE_FRONTMATTER = 'update_frontmatter',
  ACTIVATE = 'activate_tools',
  REVERT = 'revert',
  GET_MOST_RECENT_ARTIFACT = 'get_most_recent_artifact',
  GET_ARTIFACT_BY_ID = 'get_artifact_by_id',
  USER_CONFIRM = 'user_confirm',
  HELP = 'help',
  STOP = 'stop',
  THANK_YOU = 'thank_you',
  NEW_SESSION = 'new_session',
  BUILD_SEARCH_INDEX = 'build_search_index',
  SEARCH = 'search',
  SEARCH_MORE = 'search_more',
  SPEECH = 'speech',
  IMAGE = 'image',
  SHOW_WIDGET = 'show_widget',
  WIDGET_ACTION = 'widget_action',
  WIDGET_QUERY = 'widget_query',
  TODO_WRITE = 'todo_write',
  SPAWN_SUBAGENT = 'spawn_subagent',
  SWITCH_AGENT_CAPACITY = 'switch_agent_capacity',
  RECALL_COMPACTED_CONTEXT = 'recall_compacted_context',
  /** Local shell transcript; model may call it — execution always requires user confirmation in the client. */
  SHELL = 'shell',
  /** Run an enabled user-defined command by id (same entry point as slash commands). Super agent only. */
  RUN_COMMAND = 'run_command',
}
