import esbuild from 'esbuild';
import process from 'process';
import { sharedExternal } from './esbuild.shared.mjs';
import path from 'path';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function noInternalRuntimeImportsPlugin() {
  return {
    name: 'no-internal-runtime-imports',
    setup(build) {
      build.onResolve({ filter: /^internal\// }, args => {
        if (args.importer && args.importer.includes(`${path.sep}internal${path.sep}`)) {
          return null;
        }

        if (args.importer && args.importer.includes(`${path.sep}src${path.sep}`)) {
          return {
            errors: [
              {
                text:
                  `Forbidden import "${args.path}" from "${args.importer}". ` +
                  `Main bundle must not import "internal/*" directly. ` +
                  `Use getBundledInternal(...) instead (second-build payload).`,
              },
            ],
          };
        }

        return null;
      });
    },
  };
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  plugins: [],
  loader: { '.svg': 'text', '.md': 'text' },
  external: [
    'ai',
    '@ai-sdk/anthropic',
    '@ai-sdk/elevenlabs',
    '@ai-sdk/google',
    '@ai-sdk/hume',
    '@ai-sdk/openai',
    '@ai-sdk/openai-compatible',
    '@ai-sdk/mcp',
    'ollama-ai-provider-v2',
    'node-pty',
    '@xterm/xterm',
    '@xterm/addon-fit',
    '@xterm/addon-serialize',
    'socket.io',
    'socket.io-client',
    'strip-ansi',
    'mustache',
    'dexie',
    'crypto-js',
    'chrono-node',
    'i18next',
    ...sharedExternal,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
