import esbuild from 'esbuild';
import process from 'process';
import { sharedExternal } from './esbuild.shared.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  loader: { '.svg': 'text', '.md': 'text' },
  external: [
    'ai',
    '@ai-sdk/anthropic',
    '@ai-sdk/deepseek',
    '@ai-sdk/elevenlabs',
    '@ai-sdk/google',
    '@ai-sdk/groq',
    '@ai-sdk/hume',
    '@ai-sdk/openai',
    '@ai-sdk/openai-compatible',
    'ollama-ai-provider-v2',
    ...sharedExternal,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
