import { normalizePath, Platform } from 'obsidian';
import type StewardPlugin from 'src/main';
import { logger } from 'src/utils/logger';
import { compareSemverVersions } from 'src/utils/compareSemver';
import {
  NODE_PTY_INSTALLER_LATEST_BASENAME,
  NODE_PTY_INSTALLER_TEMPLATE_VERSION,
  NODE_PTY_PREBUILT_OWNER,
  NODE_PTY_PREBUILT_PACKAGE_VERSION,
  NODE_PTY_PREBUILT_REPO,
  buildNodePtyInstallerVersionedBasename,
} from 'src/constants/nodePtyInstallerConstants';
import {
  getNodePrebuildModulesFromEmbeddedNodeVersion,
  getNodePtyPrebuiltOsArchForCurrentProcess,
} from './nodePtyInstallEnv';

const INSTALLER_META_LINE_PREFIX = '# steward-installer-meta:';

export type ParsedInstallerMeta = {
  pluginVersion: string | null;
  templateVersion: string | null;
};

/**
 * Reads Steward-generated installer script metadata from the header comment.
 */
export function parseStewardInstallerMeta(content: string): ParsedInstallerMeta {
  const head = content.split(/\r?\n/).slice(0, 50);
  for (const line of head) {
    const trimmed = line.trim();
    if (!trimmed.startsWith(INSTALLER_META_LINE_PREFIX)) {
      continue;
    }
    const rest = trimmed.slice(INSTALLER_META_LINE_PREFIX.length).trim();
    const pluginMatch = rest.match(/plugin-version=([^\s]+)/);
    const templateMatch = rest.match(/template=(\d+)/);
    return {
      pluginVersion: pluginMatch?.[1] ?? null,
      templateVersion: templateMatch?.[1] ?? null,
    };
  }
  return { pluginVersion: null, templateVersion: null };
}

function buildInstallerScriptBody(params: {
  pluginVersion: string;
  /** Stock Node ABI for node-v* tarball (from process.versions.node + ABI registry) */
  nodePrebuiltModules: string;
  /** Obsidian embedded Node semver (for debugging / overrides) */
  embeddedNodeVersion: string;
  defaultOsArch: string;
}): string {
  const pkgVer = NODE_PTY_PREBUILT_PACKAGE_VERSION;
  const owner = NODE_PTY_PREBUILT_OWNER;
  const repo = NODE_PTY_PREBUILT_REPO;
  const tmpl = NODE_PTY_INSTALLER_TEMPLATE_VERSION;
  const nodeMod = params.nodePrebuiltModules.replace(/[^\d]/g, '');
  const nodeVer = params.embeddedNodeVersion.replace(/\s+/g, '');

  return `#!/usr/bin/env bash
# Generated by Obsidian Steward — interactive CLI (TTY) helper. Safe to re-run.
${INSTALLER_META_LINE_PREFIX} plugin-version=${params.pluginVersion} template=${tmpl} prebuilt-pkg=${pkgVer} node=${nodeVer} node-modules=${nodeMod}
#
# Downloads node-pty-prebuilt-multiarch **node-v\${NODE_MODULES}** only (stock Node ABI for
# process.versions.node ${nodeVer}, not Electron process.versions.modules).
#
# Defaults match Obsidian's host OS (not WSL uname). Override ABI if needed:
#   NODE_MODULES=111 bash ${NODE_PTY_INSTALLER_LATEST_BASENAME}
#
# Usage: ${NODE_PTY_INSTALLER_LATEST_BASENAME} [DEST_DIR]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
NODE_PTY_PREBUILT_VERSION="\${NODE_PTY_PREBUILT_VERSION:-${pkgVer}}"
NODE_MODULES="\${NODE_MODULES:-${nodeMod}}"
DEFAULT_OS_ARCH="\${DEFAULT_OS_ARCH:-${params.defaultOsArch}}"

if [[ -z "\${NODE_MODULES:-}" ]]; then
  echo "NODE_MODULES is empty. Update Steward / nodeAbiRegistry.json or set NODE_MODULES to a published node-v* ABI." >&2
  exit 1
fi

DEST_DIR="\${1:-"$SCRIPT_DIR/node-pty-prebuilt"}"
mkdir -p "$DEST_DIR"

resolve_os_arch() {
  case "$(uname -s 2>/dev/null)" in
    Darwin*)
      case "$(uname -m 2>/dev/null)" in
        arm64) echo "darwin-arm64" ;;
        *) echo "darwin-x64" ;;
      esac
      ;;
    Linux*)
      local musl=0
      if ldd --version 2>&1 | grep -qi musl; then musl=1; fi
      local prefix="linux"
      [[ "$musl" -eq 1 ]] && prefix="linuxmusl"
      case "$(uname -m 2>/dev/null)" in
        aarch64|arm64) echo "\${prefix}-arm64" ;;
        armv7l|armv6l|arm*) echo "\${prefix}-arm" ;;
        i686|i386) echo "\${prefix}-ia32" ;;
        *) echo "\${prefix}-x64" ;;
      esac
      ;;
    MINGW*|MSYS*|CYGWIN*)
      case "$(uname -m 2>/dev/null)" in
        i686|i386) echo "win32-ia32" ;;
        *) echo "win32-x64" ;;
      esac
      ;;
    *)
      echo "$DEFAULT_OS_ARCH"
      ;;
  esac
}

if [[ "\${STW_USE_RUNTIME_PLATFORM:-}" == "1" ]]; then
  OS_ARCH="$(resolve_os_arch)"
else
  OS_ARCH="\${OS_ARCH:-$DEFAULT_OS_ARCH}"
fi

TAG="v\${NODE_PTY_PREBUILT_VERSION}"
TMP="\${DEST_DIR}/.stw-node-pty-download.tar.gz"
ASSET="node-pty-prebuilt-multiarch-v\${NODE_PTY_PREBUILT_VERSION}-node-v\${NODE_MODULES}-\${OS_ARCH}.tar.gz"
URL="https://github.com/${owner}/${repo}/releases/download/\${TAG}/\${ASSET}"

if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required to download the prebuilt binary." >&2
  exit 1
fi

echo "Downloading $ASSET ..."
curl -fsSL "$URL" -o "$TMP"
tar -xzf "$TMP" -C "$DEST_DIR"
rm -f "$TMP"
echo "Extracted into $DEST_DIR"
`;
}

export class NodePtyInstallerScriptService {
  constructor(private readonly plugin: StewardPlugin) {}

  /**
   * Ensures ${NODE_PTY_INSTALLER_LATEST_BASENAME} exists in the Steward folder.
   * When the plugin version increases, renames the previous "latest" script to a versioned filename.
   */
  public async sync(): Promise<void> {
    if (!Platform.isDesktopApp) {
      return;
    }

    try {
      const stewardFolder = normalizePath(this.plugin.settings.stewardFolder);
      const latestPath = `${stewardFolder}/${NODE_PTY_INSTALLER_LATEST_BASENAME}`;
      const currentPluginVersion = this.plugin.manifest.version.replace(/^v/i, '');

      const latestFile = this.plugin.app.vault.getFileByPath(latestPath);
      if (latestFile) {
        const prevContent = await this.plugin.app.vault.read(latestFile);
        const { pluginVersion: embeddedVersion } = parseStewardInstallerMeta(prevContent);

        if (embeddedVersion && compareSemverVersions(currentPluginVersion, embeddedVersion) > 0) {
          const versionedBasename = buildNodePtyInstallerVersionedBasename(embeddedVersion);
          const versionedPath = `${stewardFolder}/${versionedBasename}`;
          await this.removeIfExists(versionedPath);
          await this.plugin.app.fileManager.renameFile(latestFile, versionedPath);
        }
      }

      const embeddedNode = process.versions.node ?? '';
      const nodePrebuiltModules = getNodePrebuildModulesFromEmbeddedNodeVersion(embeddedNode) ?? '';
      if (!nodePrebuiltModules) {
        logger.warn(
          `NodePtyInstallerScriptService: no node prebuild ABI mapped for process.versions.node=${embeddedNode}; set NODE_MODULES when running the installer or refresh src/constants/nodeAbiRegistry.json`
        );
      }

      const body = buildInstallerScriptBody({
        pluginVersion: currentPluginVersion,
        nodePrebuiltModules,
        embeddedNodeVersion: embeddedNode,
        defaultOsArch: getNodePtyPrebuiltOsArchForCurrentProcess(),
      });

      const latestNow = this.plugin.app.vault.getFileByPath(latestPath);
      if (latestNow) {
        const existing = await this.plugin.app.vault.read(latestNow);
        if (existing === body) {
          return;
        }
        await this.plugin.app.vault.modify(latestNow, body);
        return;
      }

      await this.plugin.app.vault.create(latestPath, body);
    } catch (error) {
      logger.error('NodePtyInstallerScriptService.sync failed:', error);
    }
  }

  private async removeIfExists(path: string): Promise<void> {
    const f = this.plugin.app.vault.getFileByPath(path);
    if (f) {
      await this.plugin.app.vault.delete(f);
    }
  }
}
