import { normalizePath, Platform } from 'obsidian';
import type StewardPlugin from 'src/main';
import { logger } from 'src/utils/logger';
import { compareSemverVersions } from 'src/utils/compareSemver';
import {
  NODE_PTY_INSTALLER_LATEST_BASENAME,
  NODE_PTY_INSTALLER_LATEST_PS1_BASENAME,
  NODE_PTY_INSTALLER_TEMPLATE_VERSION,
  NODE_PTY_PREBUILT_OWNER,
  NODE_PTY_PREBUILT_PACKAGE_VERSION,
  NODE_PTY_PREBUILT_REPO,
  buildNodePtyInstallerVersionedBasename,
  buildNodePtyInstallerVersionedPs1Basename,
} from 'src/constants/nodePtyInstallerConstants';
import { getNodePtyPrebuiltOsArchForCurrentProcess } from './nodePtyInstallEnv';

const INSTALLER_META_LINE_PREFIX = '# steward-installer-meta:';

export type ParsedInstallerMeta = {
  pluginVersion: string | null;
  templateVersion: string | null;
};

export function parseStewardInstallerMeta(content: string): ParsedInstallerMeta {
  const head = content.split(/\r?\n/).slice(0, 50);
  for (const line of head) {
    const trimmed = line.trim();
    if (!trimmed.startsWith(INSTALLER_META_LINE_PREFIX)) {
      continue;
    }
    const rest = trimmed.slice(INSTALLER_META_LINE_PREFIX.length).trim();
    const pluginMatch = rest.match(/plugin-version=([^\s]+)/);
    const templateMatch = rest.match(/template=(\d+)/);
    return {
      pluginVersion: pluginMatch?.[1] ?? null,
      templateVersion: templateMatch?.[1] ?? null,
    };
  }
  return { pluginVersion: null, templateVersion: null };
}

function buildInstallerScriptBody(params: {
  pluginVersion: string;
  defaultOsArch: string;
}): string {
  const pkgVer = NODE_PTY_PREBUILT_PACKAGE_VERSION;
  const owner = NODE_PTY_PREBUILT_OWNER;
  const repo = NODE_PTY_PREBUILT_REPO;
  const tmpl = NODE_PTY_INSTALLER_TEMPLATE_VERSION;
  const nodeVer = '20';
  const nodeMod = '115';

  return `#!/usr/bin/env bash
# Generated by Obsidian Steward — interactive CLI (TTY) helper. Safe to re-run.
${INSTALLER_META_LINE_PREFIX} plugin-version=${params.pluginVersion} template=${tmpl} prebuilt-pkg=${pkgVer} node=${nodeVer} node-modules=${nodeMod}
#
# Windows (native PowerShell): use ${NODE_PTY_INSTALLER_LATEST_PS1_BASENAME} in the same folder.
#
# Downloads node-pty-prebuilt-multiarch **node-v${nodeMod}** (Node ${nodeVer}.x ABI).
# Uses independent Node.js (not Obsidian's embedded Node).
#
# Defaults match Obsidian's host OS (not WSL uname). Override OS_ARCH if needed:
#   OS_ARCH=linux-x64 bash ${NODE_PTY_INSTALLER_LATEST_BASENAME}
#
# Usage: ${NODE_PTY_INSTALLER_LATEST_BASENAME} [DEST_DIR]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
NODE_PTY_PREBUILT_VERSION="\${NODE_PTY_PREBUILT_VERSION:-${pkgVer}}"
NODE_MODULES="\${NODE_MODULES:-${nodeMod}}"
DEFAULT_OS_ARCH="\${DEFAULT_OS_ARCH:-${params.defaultOsArch}}"

DEST_DIR="\${1:-"$SCRIPT_DIR/node-pty-prebuilt"}"
mkdir -p "$DEST_DIR"

resolve_os_arch() {
  case "$(uname -s 2>/dev/null)" in
    Darwin*)
      case "$(uname -m 2>/dev/null)" in
        arm64) echo "darwin-arm64" ;;
        *) echo "darwin-x64" ;;
      esac
      ;;
    Linux*)
      local musl=0
      if ldd --version 2>&1 | grep -qi musl; then musl=1; fi
      local prefix="linux"
      [[ "$musl" -eq 1 ]] && prefix="linuxmusl"
      case "$(uname -m 2>/dev/null)" in
        aarch64|arm64) echo "\${prefix}-arm64" ;;
        armv7l|armv6l|arm*) echo "\${prefix}-arm" ;;
        i686|i386) echo "\${prefix}-ia32" ;;
        *) echo "\${prefix}-x64" ;;
      esac
      ;;
    MINGW*|MSYS*|CYGWIN*)
      case "$(uname -m 2>/dev/null)" in
        i686|i386) echo "win32-ia32" ;;
        *) echo "win32-x64" ;;
      esac
      ;;
    *)
      echo "$DEFAULT_OS_ARCH"
      ;;
  esac
}

if [[ "\${STW_USE_RUNTIME_PLATFORM:-}" == "1" ]]; then
  OS_ARCH="$(resolve_os_arch)"
else
  OS_ARCH="\${OS_ARCH:-$DEFAULT_OS_ARCH}"
fi

TAG="v\${NODE_PTY_PREBUILT_VERSION}"
TMP="\${DEST_DIR}/.stw-node-pty-download.tar.gz"
ASSET="node-pty-prebuilt-multiarch-v\${NODE_PTY_PREBUILT_VERSION}-node-v\${NODE_MODULES}-\${OS_ARCH}.tar.gz"
URL="https://github.com/${owner}/${repo}/releases/download/\${TAG}/\${ASSET}"

if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required to download the prebuilt binary." >&2
  exit 1
fi

echo "Downloading $ASSET ..."
curl -fsSL "$URL" -o "$TMP"
tar -xzf "$TMP" -C "$DEST_DIR"
rm -f "$TMP"
echo "Extracted into $DEST_DIR"
`;
}

/** Native Windows installer (PowerShell). Bash {@link buildInstallerScriptBody} does not run in cmd/PowerShell. */
function buildInstallerPowerShellBody(params: {
  pluginVersion: string;
  defaultOsArch: string;
}): string {
  const pkgVer = NODE_PTY_PREBUILT_PACKAGE_VERSION;
  const owner = NODE_PTY_PREBUILT_OWNER;
  const repo = NODE_PTY_PREBUILT_REPO;
  const tmpl = NODE_PTY_INSTALLER_TEMPLATE_VERSION;
  const nodeVer = '20';
  const nodeMod = '115';
  const da = params.defaultOsArch;

  return [
    '# Generated by Obsidian Steward — interactive CLI (TTY) helper. Safe to re-run.',
    `# steward-installer-meta: plugin-version=${params.pluginVersion} template=${tmpl} prebuilt-pkg=${pkgVer} node=${nodeVer} node-modules=${nodeMod}`,
    '#',
    `# Downloads node-pty-prebuilt-multiarch **node-v${nodeMod}** (Node ${nodeVer}.x ABI).`,
    '# Uses independent Node.js (not Obsidian\'s embedded Node).',
    '#',
    '# Defaults match Obsidian\'s host when this file was generated. Override OS_ARCH if needed:',
    `#   \\$env:OS_ARCH = 'linux-x64'; .\\${NODE_PTY_INSTALLER_LATEST_PS1_BASENAME}`,
    '#',
    `# macOS / Linux / Git Bash on Windows: prefer ${NODE_PTY_INSTALLER_LATEST_BASENAME}.`,
    '#',
    '# Run:',
    `#   powershell -NoProfile -ExecutionPolicy Bypass -File .\\${NODE_PTY_INSTALLER_LATEST_PS1_BASENAME}`,
    '#',
    'param(',
    '  [Parameter(Position = 0)]',
    '  [string] $DestDir = ""',
    ')',
    '',
    "$ErrorActionPreference = 'Stop'",
    '',
    '$ScriptDir = $PSScriptRoot',
    'if ([string]::IsNullOrWhiteSpace($DestDir)) {',
    "  $DestDir = Join-Path $ScriptDir 'node-pty-prebuilt'",
    '}',
    '',
    "$NODE_PTY_PREBUILT_VERSION = if ($null -ne $env:NODE_PTY_PREBUILT_VERSION -and $env:NODE_PTY_PREBUILT_VERSION -ne '') {",
    '  $env:NODE_PTY_PREBUILT_VERSION',
    '} else {',
    `  '${pkgVer}'`,
    '}',
    '',
    "$NODE_MODULES = if ($null -ne $env:NODE_MODULES -and $env:NODE_MODULES -ne '') {",
    '  $env:NODE_MODULES',
    '} else {',
    `  '${nodeMod}'`,
    '}',
    '',
    "$DEFAULT_OS_ARCH = if ($null -ne $env:DEFAULT_OS_ARCH -and $env:DEFAULT_OS_ARCH -ne '') {",
    '  $env:DEFAULT_OS_ARCH',
    '} else {',
    `  '${da}'`,
    '}',
    '',
    'function Resolve-StwWinArch {',
    '  if ($env:PROCESSOR_ARCHITECTURE -eq \'x86\') {',
    "    return 'win32-ia32'",
    '  }',
    "  return 'win32-x64'",
    '}',
    '',
    'if ($env:STW_USE_RUNTIME_PLATFORM -eq \'1\') {',
    '  $OS_ARCH = Resolve-StwWinArch',
    "} elseif ($null -ne $env:OS_ARCH -and $env:OS_ARCH -ne '') {",
    '  $OS_ARCH = $env:OS_ARCH',
    '} else {',
    '  $OS_ARCH = $DEFAULT_OS_ARCH',
    '}',
    '',
    '$ver = $NODE_PTY_PREBUILT_VERSION.Trim()',
    '$ASSET = "node-pty-prebuilt-multiarch-v$ver-node-v$NODE_MODULES-$OS_ARCH.tar.gz"',
    `$URL = "https://github.com/${owner}/${repo}/releases/download/v$ver/$ASSET"`,
    '$TMP = Join-Path $DestDir \'.stw-node-pty-download.tar.gz\'',
    '',
    'New-Item -ItemType Directory -Force -Path $DestDir | Out-Null',
    '',
    'Write-Host "Downloading $ASSET ..."',
    'try {',
    '  Invoke-WebRequest -Uri $URL -OutFile $TMP -UseBasicParsing',
    '} catch {',
    '  Write-Error "Download failed."',
    '  exit 1',
    '}',
    '',
    '$tar = Get-Command tar -ErrorAction SilentlyContinue',
    'if (-not $tar) {',
    "  Write-Error 'tar is required to extract the prebuilt binary (included in Windows 10 1903+).'",
    '  exit 1',
    '}',
    '',
    '& tar -xzf $TMP -C $DestDir',
    'if ($LASTEXITCODE -ne 0) {',
    '  exit $LASTEXITCODE',
    '}',
    '',
    'Remove-Item -Force $TMP -ErrorAction SilentlyContinue',
    'Write-Host "Extracted into $DestDir"',
  ].join('\n');
}

export class NodePtyInstallerScriptService {
  constructor(private readonly plugin: StewardPlugin) {}

  public async sync(): Promise<void> {
    if (!Platform.isDesktopApp) {
      return;
    }

    try {
      const stewardFolder = normalizePath(this.plugin.settings.stewardFolder);
      const latestShPath = `${stewardFolder}/${NODE_PTY_INSTALLER_LATEST_BASENAME}`;
      const latestPs1Path = `${stewardFolder}/${NODE_PTY_INSTALLER_LATEST_PS1_BASENAME}`;
      const currentPluginVersion = this.plugin.manifest.version.replace(/^v/i, '');

      await this.maybeRenameLatestInstallersOnPluginUpgrade({
        stewardFolder,
        currentPluginVersion,
        latestShPath,
        latestPs1Path,
      });

      const defaultOsArch = getNodePtyPrebuiltOsArchForCurrentProcess();
      const shBody = buildInstallerScriptBody({
        pluginVersion: currentPluginVersion,
        defaultOsArch,
      });
      const psBody = buildInstallerPowerShellBody({
        pluginVersion: currentPluginVersion,
        defaultOsArch,
      });

      const shFile = this.plugin.app.vault.getFileByPath(latestShPath);
      const psFile = this.plugin.app.vault.getFileByPath(latestPs1Path);
      const shExisting = shFile ? await this.plugin.app.vault.read(shFile) : null;
      const psExisting = psFile ? await this.plugin.app.vault.read(psFile) : null;

      if (shExisting === shBody && psExisting === psBody) {
        return;
      }

      if (!shFile) {
        await this.plugin.app.vault.create(latestShPath, shBody);
      } else if (shExisting !== shBody) {
        await this.plugin.app.vault.modify(shFile, shBody);
      }

      if (!psFile) {
        await this.plugin.app.vault.create(latestPs1Path, psBody);
      } else if (psExisting !== psBody) {
        await this.plugin.app.vault.modify(psFile, psBody);
      }
    } catch (error) {
      logger.error('NodePtyInstallerScriptService.sync failed:', error);
    }
  }

  private async maybeRenameLatestInstallersOnPluginUpgrade(params: {
    stewardFolder: string;
    currentPluginVersion: string;
    latestShPath: string;
    latestPs1Path: string;
  }): Promise<void> {
    const shFile = this.plugin.app.vault.getFileByPath(params.latestShPath);
    if (shFile) {
      const prevContent = await this.plugin.app.vault.read(shFile);
      const { pluginVersion: embeddedVersion } = parseStewardInstallerMeta(prevContent);

      if (embeddedVersion && compareSemverVersions(params.currentPluginVersion, embeddedVersion) > 0) {
        const versionedShPath = `${params.stewardFolder}/${buildNodePtyInstallerVersionedBasename(embeddedVersion)}`;
        await this.removeIfExists(versionedShPath);
        await this.plugin.app.fileManager.renameFile(shFile, versionedShPath);

        const psLatest = this.plugin.app.vault.getFileByPath(params.latestPs1Path);
        if (psLatest) {
          const versionedPs1Path = `${params.stewardFolder}/${buildNodePtyInstallerVersionedPs1Basename(embeddedVersion)}`;
          await this.removeIfExists(versionedPs1Path);
          await this.plugin.app.fileManager.renameFile(psLatest, versionedPs1Path);
        }
      }

      return;
    }

    const psOnly = this.plugin.app.vault.getFileByPath(params.latestPs1Path);
    if (!psOnly) {
      return;
    }

    const prevPs = await this.plugin.app.vault.read(psOnly);
    const { pluginVersion: embeddedPs } = parseStewardInstallerMeta(prevPs);

    if (!embeddedPs || compareSemverVersions(params.currentPluginVersion, embeddedPs) <= 0) {
      return;
    }

    const versionedPs1Path = `${params.stewardFolder}/${buildNodePtyInstallerVersionedPs1Basename(embeddedPs)}`;
    await this.removeIfExists(versionedPs1Path);
    await this.plugin.app.fileManager.renameFile(psOnly, versionedPs1Path);
  }

  private async removeIfExists(path: string): Promise<void> {
    const f = this.plugin.app.vault.getFileByPath(path);
    if (f) {
      await this.plugin.app.vault.delete(f);
    }
  }
}
