/**
 * Step types enumeration
 */
export enum StepType {
	LLM_EXTRACTION = 'LLM_EXTRACTION',
	SEARCH = 'SEARCH',
	MOVE_PREPARATION = 'MOVE_PREPARATION',
	MOVE_EXECUTION = 'MOVE_EXECUTION',
	CONFIRMATION_REQUEST = 'CONFIRMATION_REQUEST',
	REFERENCE_RESOLUTION = 'REFERENCE_RESOLUTION',
	INTENT_DETECTION = 'INTENT_DETECTION',
	RESULTS_STORAGE = 'RESULTS_STORAGE',
	RESULTS_FORMATTING = 'RESULTS_FORMATTING',
}
